server:
  port: 8888
neo4j:
  url: bolt://127.0.0.1:7687
  username: neo4j
  password: 123456
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false #开发时关闭缓存,不然没法看到实时页面
    prefix: classpath:/templates/ # 默认路径
    suffix: .html # 后缀




#启动后访问：http://192.168.31.56:8888/index